#reference: https://www.cnblogs.com/tufeixiaopengyou/p/14119544.html
global:
  scrape_interval:  5s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql80_1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.79.132:9100','192.168.79.132:9104']
        labels:
          instance: 'db_8.0'

  - job_name: 'zookeeper'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.79.132:7000','192.168.79.133:7000','192.168.79.134:7000']
  - job_name: 'java-examp'
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.79.1:9400"]
