{
 "title": "1 SLS MySQL监控 v2020.08.13",
 "description": "MySQL指标监控",
 "tags": [
  "Prometheus",
  "Telegraf",
  "SLS",
  "MySQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "label": "Server", "query": "mysql:connections" }
  ]
 },
 "panels": [
  { "title": "MySQL监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "启动时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(mysql:uptime{server=~\"^$Server$\"})/86400",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "查询QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(mysql:queries{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "慢查询QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(mysql:slow_queries{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "slow_queries"
    }
   ]
  },
  {
   "title": "连接数/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(mysql:connections{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "conn"
    }
   ]
  },
  {
   "title": "查询QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:queries{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "Query执行次数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(mysql:queries{server=~\"^$Server$\"})",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "查询缓存",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(mysql:qcache_free_memory{server=~\"^$Server$\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "连接数/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(mysql:connections{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "conn"
    }
   ]
  },
  {
   "title": "各类Select QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(mysql:select_full_join{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "full_join"
    },
    {
     "expr": "avg(rate(mysql:select_full_range_join{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "full_range_join"
    },
    {
     "expr": "avg(rate(mysql:select_range{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "range"
    },
    {
     "expr": "avg(irate(mysql:select_range_check{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "range_check"
    },
    {
     "expr": "avg(irate(mysql:select_scan{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "scan"
    }
   ]
  },
  {
   "title": "命令执行QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:com_insert{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_insert"
    },
    {
     "expr": "avg(irate(mysql:com_set_option{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_set_option"
    },
    {
     "expr": "avg(irate(mysql:com_show_variables{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_show_variables"
    },
    {
     "expr": "avg(irate(mysql:com_show_status{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_show_status"
    },
    {
     "expr": "avg(irate(mysql:com_admin_commands{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_admin_commands"
    },
    {
     "expr": "avg(irate(mysql:com_begin{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_begin"
    },
    {
     "expr": "avg(irate(mysql:com_commit{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_commit"
    },
    {
     "expr": "avg(irate(mysql:com_update{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "com_update"
    }
   ]
  },
  {
   "title": "慢查询QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:slow_queries{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "slow_queries"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mysql:threads_connected{server=~\"^$Server$\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "avg(mysql:threads_running{server=~\"^$Server$\"})",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:bytes_sent{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "avg(irate(mysql:bytes_received{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "临时对象",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:created_tmp_tables{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "tmp_tables"
    },
    {
     "expr": "avg(irate(mysql:created_tmp_disk_tables{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "tmp_disk_table"
    },
    {
     "expr": "avg(irate(mysql:created_tmp_files{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "tmp_files"
    }
   ]
  },
  {
   "title": "Table锁",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:table_locks_immediate{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "locks_immediate"
    },
    {
     "expr": "avg(irate(mysql:table_locks_waited{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "locks_waited"
    }
   ]
  },
  {
   "title": "Handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:handler_commit{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "handler_commit"
    },
    {
     "expr": "avg(irate(mysql:handler_delete{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "handler_delete"
    },
    {
     "expr": "avg(irate(mysql:handler_discover{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "handler_discover"
    },
    {
     "expr": "avg(irate(mysql:handler_read_key{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "handler_read_key"
    },
    {
     "expr": "avg(irate(mysql:handler_read_rnd_next{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "handler_read_rnd_next"
    },
    {
     "expr": "avg(irate(mysql:handler_write{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "handler_write"
    },
    {
     "expr": "avg(irate(mysql:handler_update{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "handler_update"
    }
   ]
  },
  {
   "title": "查询缓存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:qcache_hits{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qcache_hits"
    },
    {
     "expr": "avg(irate(mysql:qcache_inserts{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qcache_inserts"
    },
    {
     "expr": "avg(irate(mysql:qcache_not_cached{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qcache_not_cached"
    },
    {
     "expr": "avg(irate(mysql:qcache_lowmem_prunes{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qcache_lowmem_prunes"
    },
    {
     "expr": "avg(irate(mysql:qcache_queries_in_cache{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "qcache_queries_in_cache"
    }
   ]
  },
  { "title": "InnoDB 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "InnoDB插入行数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(mysql:innodb_rows_inserted{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "insert"
    }
   ]
  },
  {
   "title": "InnoDB读取行数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(mysql:innodb_rows_read{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "InnoDB CRUD行数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:innodb_rows_read{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "avg(irate(mysql:innodb_rows_inserted{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "insert"
    },
    {
     "expr": "avg(irate(mysql:innodb_rows_updated{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "update"
    },
    {
     "expr": "avg(irate(mysql:innodb_rows_deleted{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool请求QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_innodb:buffer_pool_read_requests{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "avg(irate(mysql_innodb:buffer_pool_write_requests{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "InnoDB删除行数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(mysql:innodb_rows_deleted{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "InnoDB更新行数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(mysql:innodb_rows_updated{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "InnoDB Data 读写吞吐",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql:innodb_data_written{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "avg(irate(mysql:innodb_data_read{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool命中率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(mysql_innodb:buffer_pool_read_requests{server=~\"^$Server$\"}[3m]) - rate(mysql_innodb:buffer_pool_reads{server=~\"^$Server$\"}[3m]) / rate(mysql_innodb:buffer_pool_read_requests{server=~\"^$Server$\"}[3m]))",
     "legendFormat": "read_hit"
    },
    {
     "expr": "avg(mysql_innodb:buffer_pool_pages_dirty{server=~\"^$Server$\"} / mysql_innodb:buffer_pool_pages_data{server=~\"^$Server$\"})",
     "legendFormat": "buffer_pool_dirty"
    },
    {
     "expr": "avg(mysql_innodb:buffer_pool_pages_data{server=~\"^$Server$\"} /  ( mysql_innodb:buffer_pool_pages_data{server=~\"^$Server$\"} + mysql_innodb:buffer_pool_pages_free{server=~\"^$Server$\"} ))\r",
     "legendFormat": "buffer_pool_usage"
    }
   ]
  },
  {
   "title": "InnoDB Redo 写QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_innodb:log_writes{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "avg(irate(mysql_innodb:os_log_fsyncs{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "fsync"
    },
    {
     "expr": "avg(irate(mysql_innodb:log_write_requests{server=~\"^$Server$\"}[1m]))",
     "legendFormat": "write_request"
    }
   ]
  }
 ]
}