MYSQL_SRC=~/Repos/mysql-server
#MYSQL_BLD=~/build/build-libmysqld
MYSQL_ISD=~/MySQL5.7_1
BOOST_DIR=/usr/local/boost_1_59_0
#cmake -DCMAKE_INSTALL_PREFIX=$MSQL_ISD  -DDOWNLOAD_BOOST=1 -DWITH_BOOST=$BOOST_DIR $MYSQL_SRC 
cmake -DCMAKE_INSTALL_PREFIX=$MSQL_ISD  -DWITH_EMBEDDED_SERVER=1 -DWITH_DEBUG=1 -DWITH_BOOST=$BOOST_DIR $MYSQL_SRC 
