apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30010    #外网访问端口
  type: NodePort   #端口类型
  selector:
    name: nginx
